### ISSUE TITLE
[Feature request] Add Matrix4x4 and Matrix4x3 DrawText overloads

### ISSUE THREAD

**Issue by jhm-ciberman** [FontStashSharp/FontStashSharp#16]
Currently I have two separate scene graphs, one 3D scene graph for drawing 3D stuff that uses `System.Numerics.Matrix4x4` in each node and another 2D scene graph to draw UI stuff that uses `System.Numerics.Matrix3x2` to store the world matrices. 

I currently update my scene graph with the matrix multiplications and then I extract the translation component from the global world matrix of each  node. The problem is that now that FontStashSharp supports text rotation, it's easy to extract a translation from a world matrix, but it's super expensive to extract the scale and rotation. 

I would like if you can add a new method to the `SpriteFontBase` class that supports passing a `System.Numerics.Matrix3x2`.

```csharp
public float DrawText(IFontStashRenderer renderer, StringBuilder text, Color[] colors, Matrix3x2 transform, float layerDepth = 0);
```

I think that would require to change the implementation of `IFontStashRenderer`. But I now that the library is still in it's `v0.x.x` it's the perfect time. I don't think it's necesary to remove the existing Draw method (because it would be useful to have a separate method to optimize when you don't need to use a full matrix multiplication). I think something like this would be fine: 

```csharp
public interface IFontStashRenderer
{
    void Draw(object texture, Vector2 pos, Rectangle? src, Color color, float rotation, Vector2 origin, Vector2 scale, float depth);
    void Draw(object texture, Rectangle? src, Color color, in Matrix3x2 transform, float depth);
}
```

If you need help I could try to implement it myself, but I haven't dug into the code of FontStashSharp too much. 

## Case Study

https://github.com/ThomasMiz/TrippyGL/blob/0ed9a7e124aa277f9c3b23c538d59cfde54b478b/TrippyGL/TextureBatchItem.cs

TrippyGL (used in your examples in FontStashSharp.Silk.NET) has to implement a lot of code to transform the vertices of it's TextureBatchItem with the rotation, scale, and translation, whereas inside the TextureBatcher class it has a simple DrawRaw implementation that uses only a Matrix transform to handle the transformations, but it cannot use that because FontStashSharp does not provide you with the transform matrix. 

https://github.com/ThomasMiz/TrippyGL/blob/0ed9a7e124aa277f9c3b23c538d59cfde54b478b/TrippyGL/TextureBatcher.cs#L317

**Comment by rds1983** [comment]
I dont want to add a method to IFontStashRenderer, since it would require all implementations to be updated too.
However I dont mind introducting a new interface IFontStashRenderer2 that has that method accepting parameter of type Matrix3x2.
Feel free to do the PR.
