### ISSUE TITLE
Text rotation around origin seems to be different in latest version from 1.0.7

### ISSUE THREAD

**Issue by Beyley** [FontStashSharp/FontStashSharp#40]
Im updating my project from FSS 1.0.7 to 1.1.3, and it after fixing the interface to not have rot origin, it seems to act differently, going from 
https://cdn.discordapp.com/attachments/521092043288608781/984911103156945006/smoothness.mp4
to
![a](https://i.beyleyisnot.moe/TwGeIJg.png)

(font difference is unrelated)

**Comment by Beyley** [comment]
Origin = (-50,-50), scale = 1.0
1.1.3
![testoutput](https://user-images.githubusercontent.com/34501060/173178827-13d9a5c3-4422-480c-a637-631f718cc54c.png)
1.0.7
![testoutput](https://user-images.githubusercontent.com/34501060/173178883-6f8638f3-b826-41f4-9077-fae7f7bbd2fe.png)

Origin = (-50,-50), scale = 2.0
1.1.3
![testoutput](https://user-images.githubusercontent.com/34501060/173178936-43bb890e-c96a-4ed6-ad14-d98fcb28247c.png)
1.0.7
![testoutput](https://user-images.githubusercontent.com/34501060/173178944-d9f53f7d-66ee-4d30-8e1e-2767c7ef5a9e.png)

**Comment by rds1983** [comment]
Well, the reference behavior for the origin/rotation isnt 1.0.7, but MonoGame's SpriteFont.
Check sample RotatingText. I've updated it so it renders text using both FontStashSharp and MonoGame's SpriteFont. The behavior seems similar.
![image](https://user-images.githubusercontent.com/1057289/173186933-c1c8f91d-c026-4d3f-a4c2-871ab7eb8bb4.png)

If you still need 1.0.7 behavior, I'd recommend downgrading to FontStashSharp 1.1.0.
Or forking this repo and reverting this commit: https://github.com/FontStashSharp/FontStashSharp/commit/05c806df9fbfd5ab83ad1d3783ba005a645d3152

**Comment by Beyley** [comment]
I ended up spending a day or 2 rewriting to match the new system
