### ISSUE TITLE
Replace all string parameters in Draw methods by System.ReadOnlySpan<char> to avoid allocations?

### ISSUE THREAD

**Issue by jhm-ciberman** [FontStashSharp/FontStashSharp#45]
I'm developing a custom UI system with FontStashSharp. I love this library. Thanks for developing it. It's so easy to use and so beautiful. And the newest aditions (like `IFontStashRenderer2`) are amazing.

I would propose one small but useful change. To swap the `string text` parameter in all the Draw overloads by a `System.ReadOnlySpan<char>`. This would allow to draw multiline text without extra allocations. 

**This wouldn't break any compatibility because string has an implicit conversion to ReadOnlySpan<char>**

For example, currently if I want to draw a string with word wraping, I would need to do the following in my TextBlock class:

```csharp
private string _text = string.Empty;
private List<string> _textLines = new List<string>();

public string Text
{
    get => this._text;
    set
    {
        _text = value;
        _textLines.Clear();
        // Apply word wrapping logic and split the string and put every line inside the text lines list.
        // The problem is that every string is immutable, thus generating a new allocation
    }
}

protected void Draw()
{
    foreach (var line in _textLines)
    {
        _font.Draw(line, ...etc);
    }
}

```

If the argument type is changed by a ReadOnlySpan, this would allow to apply word wrapping, per word, or per sentence effects without the need of extra allocations. 

ReadOnlySpan<char> is a struct (so it does not allocates in the heap) and it is defined as `ReadOnlySpan(char[]? array, int start, int length)`. So for a word wrapping system (or something similar) the system would need to create a `List<ReadOnlySpan<char>> _textLines`. 

For example, a simple WordWrap alogorithm without extra allocations would be like this: 

```csharp
private void WordWrap()
{
    this._textLines.Clear();
    int firstCharIndex = 0;
    int charCount = 0;
    for (int i = 0; i < this.Text.Length; i++)
    {
        charCount++;
        if (this.Text[i] == ' ')
        {
            var span = new ReadOnlySpan<char>(this.Text, firstCharIndex, charCount);
            Vector2 size = this._font.MeasureText(span, ...etc);
            if (size.X > this.Width)
            {
                  this._textLines.Add(span);
                  firstCharIndex += charCount + 1;
             }
        }
    }

    var span = new ReadOnlySpan<char>(this.Text, firstCharIndex, charCount);
    this._textLines.Add(span);
}
```

**Comment by rds1983** [comment]
Hi,
Sorry for the late response. I like the idea. However it would require FSS be updated to .net standard 2.1(from .net standard 2.0).
And it would make it problematic for BRUTE users to port their projects to say nintendo switch.
Probably I'll add my own type(StringSegment) that allow to specify part of the string.

**Comment by jhm-ciberman** [comment]
I understand your concerns. But I'm not sure that is a good idea to add your own type. Maybe is easier to wrap the new methods in `#IF NETSTANDARD2_1`:

```csharp
#IF NETSTANDARD2_1

public void DrawText(ReadOnlySpan<char> text, blablabla...)
{
   //
}

#ENDIF
```

**Comment by rds1983** [comment]
There is a problem with such approach: if a user will use netstandard 2.1 version of the library, they might have a problem BRUTEing it.
Hence I'd stick with my own type.

**Comment by jhm-ciberman** [comment]
Oh, I googled "Brute" and it lead me to this website http://brute.rocks/, but when I click on "Documentation" or "Releases" it gives me a 404. I'm not sure it's worth it creating your own type. Microsoft is pushing hard with the use of ReadOnlySpan in all of it's apis. If some user wants to use that "BRUTE" software, he can simply use netstandard2.0 and it will work without any change. Nuget will find the corresponding binary for him. 

If you are still thinking in creating your own type, try to make it a `readonly ref struct` so it can't be allocated in the heap or boxed, in the same way `ReadOnlySpan<T>` does. Something like this:

```csharp
public readonly ref struct StringSpan
{
  //
}
```

**Comment by rds1983** [comment]
Yeah, that's correct BRUTE. That tool is used to run MG/FNA apps on platforms that don't have .NET support like Nintendo Switch. AFAIK BRUTE supports maximum "net452". Hence I've chosen ".net standard 2.0"(well, it's not really "net452", but closest among targets that arent deprecated yet).
BRUTE doesnt support Span in any form. Hence I've would have to go with my own type.

**Comment by jhm-ciberman** [comment]
I think you could still use ReadOnlySpan and BRUTE users can target net2.0 and use the old DrawOverloads the same way they are doing right now. 

But do as you like. Both ways would represent an improvement over the existing apis. ☺️

**Comment by rds1983** [comment]
well, custom type would let even a BRUTE user to use the new functionality.

**Comment by jhm-ciberman** [comment]
True. You got a good point there. And I am not aware of any special optimization of the ReadOnlySpan (as long as the new type is a ref struct to avoid boxing). The extra overhead of type converting between read only span and StringSpan would be almost negligible. So I am okay with this ☺️

**Comment by jhm-ciberman** [comment]
What do you mean by "BRUTEing"?

**Comment by jhm-ciberman** [comment]
I know a lot of time has passed, but. It's not possible to convert a `ReadOnlySpan<char>` to a `FontStashSharp.StringSegment`. 

The `ReadOnlySpan<char>` intentionaly has no access to the internal string/array. But `FontStashSharp.StringSegment` requires a `string` in the parameter. 
This makes extremely cumbersome to work with existing C# APIs.
