### ISSUE TITLE
Use a single atlas for multiple font effects

### ISSUE THREAD

**Issue by Beyley** [FontStashSharp/FontStashSharp#63]
Currently to use multiple font effects you have to create multiple font systems (i cant find a way without doing it at least)
This would use much less vram as you need less texture atlases
Haiving Effect and effectparameters on the Font.DrawText call would be the most logical place to put them so you can use multiple effects on a single font system

**Comment by rds1983** [comment]
Nice idea. Probably rich text syntax could be also updated with the new command '/e' that would turn on an effect.
