### ISSUE TITLE
RichTextLayout.Size isn't accurate when Height is set

### ISSUE THREAD

**Issue by brettmjohnson** [FontStashSharp/FontStashSharp#85]
RichTextLayout.Size isn't accurate when Width and Height is set.

For example, if I have a font at 24 and Height set to 36, I would expect Size.Y to return 24 since only a single line is being displayed. And I would expect the width to be the width of the displayed line (including ellipses if set).

Instead, Size returns the dimensions of the string as if Width and Height are not set.

I could see this being by design, but it would be helpful to get the accurate display dimensions also. Is there another way?

**Comment by rds1983** [comment]
It's not by design, but straight up bug. Thanks for reporting.
