### ISSUE TITLE
RichText styles /tu and /ts are broken

### ISSUE THREAD

**Issue by Telespaz** [FontStashSharp/FontStashSharp#87]
Tested with 1.3.5 and 1.3.6 in both versions it is not working anymore.

**Comment by rds1983** [comment]
Check RichText sample. It has /tu and it works.
![image](https://github.com/FontStashSharp/FontStashSharp/assets/1057289/28cbcec4-a589-4681-a201-4f8a05a7421e)

**Comment by Telespaz** [comment]
Thanks for pointing out i did some try and error and find out my resolution was to high why it was not rendering the underline or strikethrough effect for some reason. I had the following settings

FontSystemDefaults.FontResolutionFactor = 8.0f;
FontSystemDefaults.KernelWidth = 8;
FontSystemDefaults.KernelHeight = 8;
